kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: influxdb-v1
  annotations:
    # volume.beta.kubernetes.io/storage-class: "do-block-storage"
    volume.beta.kubernetes.io/storage-class: "gp2"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
